name: Anonymize Data

on:
  workflow_dispatch:
    inputs:
      DATA:
        description: 'Data File'
        required: true
        type: choice
        default: 20230910.csv
        options:
          - 20230910.csv
          - 20230909.csv

jobs:
  check-data-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install python dependencies
        run: |
          mkdir output &&
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Get data and print summaries
        run: python get-data.py '${{ inputs.DATA }}'
      - name: Cache summary data file
        id: summary-data-file
        uses: actions/cache@v3
        with:
          key: summary-data-file-${{ inputs.DATA }}
          path: ./output
  anonymize-data-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: [check-data-dev]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Anonymize data and print summaries
        run: python anonymize-data.py 'data-files/${{ inputs.DATA }}'

  check-data-prod:
    runs-on: ubuntu-latest
    needs: [check-data-dev,anonymize-data-dev]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install python dependencies
        run: |
          mkdir output &&
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Get data and print summaries
        run: python get-data.py '${{ inputs.DATA }}'
      - name: Cache summary data file
        id: summary-data-file
        uses: actions/cache@v3
        with:
          key: summary-data-file-${{ inputs.DATA }}
          path: ./output
  anonymize-data-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: [check-data-dev,anonymize-data-dev,check-data-prod]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Anonymize data and print summaries
        run: python anonymize-data.py 'data-files/${{ inputs.DATA }}'
      