name: Data Deletion Workflow

on:
  workflow_dispatch:

jobs:
  data-deletion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          # - name: Install dependencies
          #   run: |
          #     python -m pip install --upgrade pip
          #     pip install flake8 pytest
          #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          #   ref: # branch
          #     my_other_branch

      - name: Get 'data_20230909.csv' data, print summaries
        run: |
          python get_data.py 'data-files/data_20230909.csv'
